# Generated by Django 3.0.6 on 2020-06-02 23:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_code', models.CharField(max_length=50)),
                ('minutes', models.IntegerField()),
                ('internet', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_type', models.CharField(max_length=8)),
                ('operator', models.CharField(max_length=6)),
                ('ddds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
