# Generated by Django 3.0.6 on 2020-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='internet',
            field=models.CharField(max_length=10),
        ),
    ]
