# Generated by Django 3.0.6 on 2020-06-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200603_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Plans',
        ),
    ]
