# Generated by Django 3.0.6 on 2020-06-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20200603_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
